apiVersion: v1
kind: Service
metadata:
  name: k8-service-rs
spec:
  type: NodePort
  ports:
  - name: nginx
    nodePort: 30100 
    port: 81
    protocol: TCP
    targetPort: 80 
  selector:
    app: k8-service-rs-pod
